### ISSUE TITLE
ImportError при попытке запустить analyzer-api

### ISSUE THREAD

**Issue by eoan-ermine** [alvassin/backendschool2019#3]
```
(env) eoanermine@DESKTOP-9T8JJ1C:~/backendschool2019$ analyzer-api
Traceback (most recent call last):
  File "/home/eoanermine/backendschool2019/env/bin/analyzer-api", line 11, in <module>
    load_entry_point('analyzer', 'console_scripts', 'analyzer-api')()
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/eoanermine/backendschool2019/analyzer/api/__main__.py", line 17, in <module>
    from analyzer.api.app import create_app
  File "/home/eoanermine/backendschool2019/analyzer/api/app.py", line 8, in <module>
    from aiohttp_apispec import setup_aiohttp_apispec, validation_middleware
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/aiohttp_apispec/__init__.py", line 1, in <module>
    from .aiohttp_apispec import AiohttpApiSpec, setup_aiohttp_apispec
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/aiohttp_apispec/aiohttp_apispec.py", line 10, in <module>
    from jinja2 import Template
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/eoanermine/backendschool2019/env/lib/python3.8/site-packages/markupsafe/__init__.py)
(env) eoanermine@DESKTOP-9T8JJ1C:~/backendschool2019$ analyzer-api
```

Как воспроизвести:

```
make devenv
make postgres
source env/bin/activate
analyzer-db upgrade head
analyzer-api
```

**Comment by eoan-ermine** [comment]
Это [проблема на стороне `aiohttp-apispec`](https://github.com/maximdanilchenko/aiohttp-apispec/issues/122)

Пишут, что в версиях v2.2.3 and v3.0.0b2 это было починено
